haproxy:
  - haproxy


haproxy_app_name: myhap
haproxy_mode: http
haproxy_enable_stats: enable
haproxy_algorithm: roundrobin
haproxy_backend_servers:
     - {name: server1, ip: 10.3.238.183, port: 80, paramstring: cookie A check}
     - {name: server2, ip: 10.3.238.90, port: 80, paramstring: cookie A check}
haproxy_stats_users:
     - {username: admin, password: P@ssword123}
